### ISSUE TITLE
Username of host machine

### ISSUE THREAD

**Issue by tt41** [pmatulis/maas-one#1]
1st, thank you very much for those scripts !
I made an installation with those recently and it worked perfectly well, very well guided ! (except after reboot ... mainly for Juju but it's more linked to Juju itself I think)
Just some script use default "username" for the host machine (used with some ssh commands)
It's not mark as "your username" and it's a bit confusing with "username" used by the nodes (it's understandable reading the scripts). [I can check my modifications in this way, so you can adjust your README file or scripts itself]
I hope my English is not too bad. It's my 1st issue on GitHub, I hope my 1st issue is ok on GitHub.

**Comment by pmatulis** [comment]
@tt41 Hi. Thanks for the issue. So you're saying that a "username@kvm-host" is what is missing like in step **Download this repo**? If not, please submit a more detailed answer of what you would like to see.

**Comment by tt41** [comment]
Sorry for the delay
Not here ...
After **Configure MAAS** in **Verify the web UI** in the README
In the script **config-nodes.sh** line 26, the username specified is "ubuntu" (and in my case, it's not, I choose an other username for my host machine ...)

I think it's the only 2 spots where it where that.
I pointed it out because your Readme is very clear, I think it's also usable for non advanced users.

I successfully installed it on a fresh machine, I noted few moments when I had to do somethings pointed with '°°°°°' at the beginning of the lines before the problem occur (the errors were clear but it can be a plus).
I join you a modified copy of your readme in this way.

[README - Copie.txt](https://github.com/pmatulis/maas-one/files/5973684/README.-.Copie.txt)

Feel free to ask if I was unclear !

**Comment by pmatulis** [comment]
Hi @tt41 , Thanks for your feedback! I will try to cover your points.

## Point 1

> Create a test instance to discover the names of the two MAAS host network
interfaces (created via `template-maas.xml`). Reference these in
`user-data-maas.yaml`, the cloud-init file for the MAAS host.
°°°°° need a ssh private key created (id_rsa.pub ? not sur it have to be named as it) ; 
    uvt-kvm create --template ./template-maas.xml test release=focal

So a little earlier in section **Download this repo** it states:

*SSH to the KVM host with agent forwarding enabled. Forward your usual personal
keys.*

`uvt-kvm` will use those keys so I think this point is satisfied right?

I repeat the need to be forwarding your keys in the **Set up the environment** section:

*This key(s) should be forwarded when initially connecting to the KVM host.*

## Point 2

> Install the public SSH key for the MAAS host 'root' user into the 'ubuntu' user
account on the KVM host:
°°°°° I needed to connect into the 10.0.0.2 host ... I this quotes were missing here (or removed by the '.md' format ? OR I miss understant and it's the "ubuntu" user of the KVM host)
    ssh root@10.0.0.2 cat /var/snap/maas/current/root/.ssh/id_rsa.pub >> /home/ubuntu/.ssh/authorized_keys

This works for me with the Bash shell. What are you using? I will consider using quotes to accommodate other shells.

## Point 3

> Confirm that the 'root' user can query libvirtd of the KVM host:
°°°°° need the KVM host to have ssh connection enable

Again, the forwarded SSH keys should handle this right?

## Point 4

> Set up local port forwarding from your desktop:
°°°°° here, the username of the host KVM depend on the name choosen (maybe just precise that)
    ssh -N -L 8002:10.0.0.2:5240 ubuntu@<kvm-host>

Yes, confirmed. I will mention this.

> Configure the nodes by running a script that was transferred earlier:
°°°°° as for the port redirection, in this script, the KVM host username is set to ubuntu by default
    ssh ubuntu@10.0.0.2 ./config-nodes.sh

This user is for the MAAS host that we created so user 'ubuntu' should be there for everyone right?
